---
- name: Include OS Specific setup tasks
  include: setup-{{ ansible_os_family }}.yml

- include: config.yml
- include: ssl.yml
- include: plugins.yml

- name: Output directory
  file:
    state: directory
    path: "{{ logstash_output_dir }}"
    owner: logstash
    group: logstash
    mode: 0775
  when: logstash_output_dir is defined

- name: Ensure Logstash is started and enabled on boot.
  service:
    name: logstash
    state: started
    enabled: "{{ logstash_enabled_on_boot }}"
